### ISSUE TITLE
Build listed jobs by their status

### ISSUE THREAD

**Issue by nicoddemus** [ESSS/err-jenkins#18]
Include `!build <status>`, so Bender will trigger the jobs listed according to their status.

Suppose we have listed:

```
0. (FAIL) alfasim-master-win64  
1. (FAIL) alfasim-master-linux64
2. (OK) alfasim-master-synthetic
```

Issuing `!build failure` would trigger builds `0` and `1`.

This would help a lot with re-issuing failed builds when listing branches created by Marvin.

The nouns we could use should be taken from here: https://github.com/ESSS/err-jenkins/blob/0cc5b70867589b9faeab77f0e07e1d69c8af4d51/esss_jenkins.py#L557-L566

(We could also review the emojis used there to actual unicode emojis instead of relying on what RC provides)

Also we should support passing multiple statuses at once: `!build failure not_started`

**Comment by prusse-martin** [comment]
I think this will cause more and more multiple jobs to be fired.
Maybe queue internally the builds and then fire one at a time? (this actually looks messy)

**Comment by nicoddemus** [comment]
Yeah probably better to just let the user enter the ids manually, it is not that hard. I'll shelve this for now. 👍
